# Generated by Django 6.0.7 on 2026-07-20 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_medicines', models.IntegerField()),
                ('medicines_names', models.JSONField(default=list)),
                ('doctor_fee', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('medicine_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'db_table': 'billing',
            },
        ),
    ]
