# Generated by Django 6.0.7 on 2026-07-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default=123456, max_length=255),
            preserve_default=False,
        ),
    ]
