# Generated by Django 6.0.7 on 2026-07-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='General Physician', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='years_of_exp',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
